name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Use GitHub Actions' ruby/setup-ruby to shorten build times
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Matches GitHub Pages' supported version
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          
      - name: Install Jekyll and bundler
        run: |
          gem install jekyll bundler
          
      - name: Build with Jekyll
        run: |
          bundle exec jekyll build --verbose
          
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
